apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingtests.app.anton.com
spec:
  scope: Namespaced
  group: app.anton.com
  names:
    kind: PingTest
    plural: pingtests
    singular: pingtest
    shortNames:
      - ping
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                count:
                  type: integer
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true